zk:
  scheduler:
    address: 127.0.0.1
    username: lin
    password: lin


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scheduler?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root


###mybatis配置###
#配置实体类的别名
mybatis:
  type-aliases-package: com.github.krystalics.d10.scheduler.dao.entity
  #指定映射文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    org:
      springframework: error

server:
  port: 8082

#  高可用策略 有两种 master-slave 主从 | multi-live 多活
schedule:
  ha:
    policy: multi-live

token:
  keyMap: { scheduler: 92e6e4ba2336a893718910810df46d7f, executorManager: 15cc5d85980ff20c679f1f2a22a6aa10, executor: ced95c1c8afb5de4a14fbbbbecd2bcef }
